---

- name: Write keyboard configration
  ansible.builtin.template:
    src: keyboard.j2
    dest: /etc/default/keyboard
    force: yes
    owner: root
    group: root
    mode: 'u=rw,go=r'
  become: yes
  notify:
    - Set keyboard configuration
